### ISSUE TITLE
Exercise 1

### ISSUE THREAD

**Issue by kcawthorn** [ualbertalib/dsc_git_workshop#6]
Kate-MacBook-Air:learn_git Kate$ git commit "Add sentence to file"
error: pathspec 'Add sentence to file' did not match any file(s) known to git
Kate-MacBook-Air:learn_git Kate$ git commit "Add sentence to file."
error: pathspec 'Add sentence to file.' did not match any file(s) known to git
Kate-MacBook-Air:learn_git Kate$ git hist
git: 'hist' is not a git command. See 'git --help'.

The most similar command is
	bisect
Kate-MacBook-Air:learn_git Kate$

**Comment by ghost** [comment]
Thanks, I forgot the "-m" flag. The command should be **git commit -m "Add sentence to file".

**Comment by ghost** [comment]
Should be fixed now.
