### ISSUE TITLE
Exercise 1 - git hist?

### ISSUE THREAD

**Issue by kcawthorn** [ualbertalib/dsc_git_workshop#7]
Kate-MacBook-Air:learn_git Kate$ git hist
git: 'hist' is not a git command. See 'git --help'.

The most similar command is
	bisect
Kate-MacBook-Air:learn_git Kate$

**Comment by ghost** [comment]
I've added a step to the exercise which will give you "git hist". This seemed like the easiest way, though it's not ideal.
