### ISSUE TITLE
Exercise 8 - git hist error

### ISSUE THREAD

**Issue by kcawthorn** [ualbertalib/dsc_git_workshop#9]
Kate-MacBook-Air:more_git Kate$ git hist
git: 'hist' is not a git command. See 'git --help'.

The most similar command is
	bisect

**Comment by ghost** [comment]
All the git hist commands rely on the .gitignore file I added to exercise one. Once that step is followed git hist should work.

**Comment by kcawthorn** [comment]
I tried, but I don't think I quite understand how to add this part properly. I will try again, but it might be one of the things for you to show me tomorrow

**Comment by ghost** [comment]
Ok, for sure.
